### ISSUE TITLE
Please also publish releases of parent pom

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Marketing-Cloud/aem-dialog-conversion#2]
in the public repo
https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/
the artifacts `cq-dialog-conversion-content` and `cq-dialog-conversion` are available, but the artifact `cq-dialog-conversion-parent` is not.

please publish `cq-dialog-conversion-parent` as well. this is required when the other artifacts are included in maven builds e.g. for deployment or downstream tooling.

**Comment by gknobloch** [comment]
Thanks @stefanseifert for reporting.
I requested the publication of the artifact, and will let you know when ready.

**Comment by gknobloch** [comment]
https://repo.adobe.com/nexus/content/repositories/releases/com/adobe/cq/cq-dialog-conversion-parent/1.0.3/ has been published.
